import UserContextProvider from "@/context/UserContext";
import "./globals.css";

export const metadata = {
  title: "PortaCode App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <UserContextProvider>
        <body>{children}</body>
      </UserContextProvider>
    </html>
  );
}
